"""create cuisines table

Revision ID: 0cbc4cf11d77
Revises: 
Create Date: 2025-05-25 19:08:22.728593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbc4cf11d77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuisines_description'), 'cuisines', ['description'], unique=False)
    op.create_index(op.f('ix_cuisines_id'), 'cuisines', ['id'], unique=False)
    op.create_index(op.f('ix_cuisines_is_available'), 'cuisines', ['is_available'], unique=False)
    op.create_index(op.f('ix_cuisines_name'), 'cuisines', ['name'], unique=False)
    op.create_index(op.f('ix_cuisines_unit_price'), 'cuisines', ['unit_price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cuisines_unit_price'), table_name='cuisines')
    op.drop_index(op.f('ix_cuisines_name'), table_name='cuisines')
    op.drop_index(op.f('ix_cuisines_is_available'), table_name='cuisines')
    op.drop_index(op.f('ix_cuisines_id'), table_name='cuisines')
    op.drop_index(op.f('ix_cuisines_description'), table_name='cuisines')
    op.drop_table('cuisines')
    # ### end Alembic commands ###
