name: from-fastapi-2-genai

services:
  app_business:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: "app_business"
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ../app_business:/app

  db_business:
    image: timescale/timescaledb-ha:pg16
    container_name: "db_business"
    environment:
      POSTGRES_DB: business
      POSTGRES_USER: youwei
      POSTGRES_PASSWORD: fromfastapi2genai
    ports:
      - "5118:5432"
    volumes:
      - data_business:/home/postgres/pgdata/data
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youwei -d business"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  net:
    driver: bridge

volumes:
  data_business:

