name: from-fastapi-2-genai

services:
  app_business:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: "app"
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ../app_business:/app

networks:
  net:
    driver: bridge